app:
  containerPort: 8501
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 2Gi
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    averageUtilization:
      cpu: 100
      memory: 100