on:
  workflow_dispatch:
name: Vault token
jobs:
  vault-login:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
        contents: read
        id-token: write
    steps:
    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault
    - name: login vault
      run: |
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=startup-bootstrap")
        echo $(echo $TOKEN | base64)
        export VAULT_ADDR="https://vault-dev.factory.social.gouv.fr"
        vault write auth/github-ci/login role=se-startup-bootstrap jwt=${{ secrets.GITHUB_TOKEN }}
